plugins {
    id("com.android.application")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

android {
    namespace = "com.example.hawwil_app"
    compileSdk = 36 // 👈 تثبيت إجباري على 36
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.example.hawwil_app"
        minSdk = flutter.minSdkVersion
        targetSdk = 36 // 👈 تثبيت إجباري على 36
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        multiDexEnabled = true // 👈 إضافة هامة جداً لمنع الانهيار بسبب حجم Firebase
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
            minifyEnabled = false // 👈 منع حذف الأكواد المهمة في نسخة الـ Release
            shrinkResources = false
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation("androidx.multidex:multidex:2.0.1") // 👈 تفعيل مكتبة MultiDex
}
