name: hawwil
description: منصة حوّل للخدمات المالية الموريتانية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
